/**
 * Cycle 14BD: server-side accessor for the imported Amazon review
 * bundle. Cards are pre-sorted by helpful_votes desc → date desc.
 *
 * Source data: data/amazon-reviews.json (regenerated by
 * scripts/ingest-amazon-reviews.ts after each fresh handoff batch).
 */
import reviewData from "@/../data/amazon-reviews.json";

export type AmazonReview = {
  id: string;
  stars: number;
  title: string;
  body: string;
  reviewer: string;
  date: string;
  verified: boolean;
  helpful_votes: number;
  images: string[];
};

export type AmazonReviewBundle = {
  handle: string;
  asin: string;
  amazon_title: string;
  avg_rating: number;
  review_count: number;
  reviews: AmazonReview[];
};

type Manifest = {
  generated_at: string;
  source: string;
  by_handle: Record<string, AmazonReviewBundle>;
};

const manifest = reviewData as Manifest;

export function getReviewsForHandle(
  handle: string | null | undefined,
): AmazonReviewBundle | null {
  if (!handle) return null;
  return manifest.by_handle[handle] ?? null;
}

/**
 * Quick aggregate (avg rating + count) keyed by handle — used by
 * ProductCard, search results, vehicle-hub Top Picks rail. Returns
 * null when no reviews are imported for that handle (callers can
 * choose to hide the stars row in that state).
 */
export function getReviewAggregate(
  handle: string | null | undefined,
): { rating: number; count: number } | null {
  const bundle = getReviewsForHandle(handle);
  if (!bundle) return null;
  return { rating: bundle.avg_rating, count: bundle.review_count };
}

export function getReviewDataSource(): string {
  return manifest.source;
}
