/**
 * Cycle 14BD: server-side accessor for the imported Amazon review
 * bundle. Cards are pre-sorted by helpful_votes desc → date desc.
 *
 * Source data: data/amazon-reviews.json (regenerated by
 * scripts/ingest-amazon-reviews.ts after each fresh handoff batch).
 */
import reviewData from "@/../data/amazon-reviews.json";

export type AmazonReview = {
  id: string;
  stars: number;
  title: string;
  body: string;
  reviewer: string;
  date: string;
  verified: boolean;
  helpful_votes: number;
  images: string[];
  // Cycle 14BI: provenance so the PDP labels imported-vs-native reviews
  // accurately for FTC disclosure. Absent = "amazon" (legacy imports).
  source?: "amazon" | "customer";
};

export type AmazonReviewBundle = {
  handle: string;
  asin: string;
  amazon_title: string;
  avg_rating: number;
  review_count: number;
  reviews: AmazonReview[];
};

type Manifest = {
  generated_at: string;
  source: string;
  by_handle: Record<string, AmazonReviewBundle>;
};

const manifest = reviewData as Manifest;

export function getReviewsForHandle(
  handle: string | null | undefined,
): AmazonReviewBundle | null {
  if (!handle) return null;
  return manifest.by_handle[handle] ?? null;
}

/**
 * Quick aggregate (avg rating + count) keyed by handle — used by
 * ProductCard, search results, vehicle-hub Top Picks rail. Returns
 * null when no reviews are imported for that handle (callers can
 * choose to hide the stars row in that state).
 */
export function getReviewAggregate(
  handle: string | null | undefined,
): { rating: number; count: number } | null {
  const bundle = getReviewsForHandle(handle);
  if (!bundle) return null;
  return { rating: bundle.avg_rating, count: bundle.review_count };
}

export function getReviewDataSource(): string {
  return manifest.source;
}

/**
 * Cycle 14BI: fold approved native (customer-submitted) reviews into the
 * imported-Amazon bundle for a handle. Pure — the DB read happens in the
 * server-only `getApprovedNativeReviews` (lib/reviews/native). Recomputes
 * avg + count across both sources; returns null only when there are zero
 * reviews from either source. Native reviews carry source:"customer" so the
 * PDP can disclose provenance accurately.
 */
export function mergeNativeReviews(
  bundle: AmazonReviewBundle | null,
  native: AmazonReview[],
  handle: string,
): AmazonReviewBundle | null {
  if ((!bundle || bundle.review_count === 0) && native.length === 0) {
    return bundle;
  }
  const base: AmazonReviewBundle =
    bundle ?? {
      handle,
      asin: "",
      amazon_title: "",
      avg_rating: 0,
      review_count: 0,
      reviews: [],
    };
  if (native.length === 0) return base;
  // Native reviews first (newest customer voice), then imported.
  const reviews = [...native, ...base.reviews];
  const avg =
    Math.round(
      (reviews.reduce((s, r) => s + r.stars, 0) / reviews.length) * 10,
    ) / 10;
  return {
    ...base,
    reviews,
    avg_rating: avg,
    review_count: reviews.length,
  };
}
