import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {
  getCategories,
  getCollection,
  getPopularVehicles,
  type CatalogProduct,
} from "@/lib/catalog";
import { withFitment } from "@/lib/fitment/match";
import { TrustRow } from "@/components/ui/trust-row";
import { Icons } from "@/components/ui/icons";
import { YmmButton } from "@/components/fitment/ymm-button";
import { getCurrentVehicle, getSubModelAnswers } from "@/lib/garage/server";
import { ProductCard } from "@/components/commerce/product-card";

// Cycle 14AA (Mike-O14AA F-7 MAJOR): page must read garage cookie at SSR
// time to flip the YMM band into "Shop your truck" mode. Setting
// `revalidate` here would cache the rendered HTML across users, which
// would freeze a single visitor's vehicle into the static blob. Switch
// to dynamic so the SSR pass sees the cookie on every request.
export const dynamic = "force-dynamic";

// Cycle 14AL (owner): popular-vehicle tiles now show each truck WITH
// a representative Stehlen part composited on (tonneau, running boards,
// rock sliders, etc.) — generated by Gemini Nano Banana 2 via
// scripts/regen-popular-vehicle-photos.ts. Source files (without the
// part) stay in /vehicle-gens/ for the per-vehicle hub pages, which
// still want the unmodified factory shot.
const POPULAR_VEHICLE_PHOTOS: Record<string, string> = {
  "ford-f-150": "/images/vehicle-gens-modded/ford-f-150.jpg",
  "chevrolet-silverado": "/images/vehicle-gens-modded/chevrolet-silverado.jpg",
  "ram-1500": "/images/vehicle-gens-modded/ram-1500.jpg",
  "toyota-tacoma": "/images/vehicle-gens-modded/toyota-tacoma.jpg",
  "jeep-wrangler": "/images/vehicle-gens-modded/jeep-wrangler.jpg",
  "toyota-tundra": "/images/vehicle-gens-modded/toyota-tundra.jpg",
  "gmc-sierra": "/images/vehicle-gens-modded/gmc-sierra.jpg",
  "nissan-frontier": "/images/vehicle-gens-modded/nissan-frontier.jpg",
};

// Cycle 14Z (Priya F-16 LOW): every other route now sets an explicit canonical;
// home was relying on Google self-canonicalizing from URL. That works, but
// leaves a consolidation gap if a `?utm_source=` or trailing-slash variant
// gets crawled. Explicit is cheap insurance.
// Cycle 14X+ (Priya F-6 HIGH): every OTHER route emits og:url + og:image,
// but the home page was inheriting only the partial layout-level OG block.
// Facebook / LinkedIn / AI scrapers (Perplexity, ChatGPT browse) that hit
// the homepage saw no image to embed. Google Discover eligibility also
// requires og:image with min 1200×630.
export const metadata: Metadata = {
  alternates: { canonical: "/" },
  openGraph: {
    url: "/",
    images: [
      {
        // Cycle 14AM (Diana hero pass): restored from
        // hero-stehlen-original.jpg.bak (1920×839, 210 KB). Earlier
        // cycle-14U crop pass shrunk it to 1280×640, which was the
        // root cause of the visible blur at desktop widths.
        url: "/images/hero-stehlen.jpg",
        width: 1920,
        height: 839,
        alt: "Stehlen Auto — Heavy-Duty Vehicle Accessories",
      },
    ],
  },
  twitter: {
    images: ["/images/hero-stehlen.jpg"],
  },
};

// Cycle 14Z batch 4 (Mike-O4 F-1): TESTIMONIALS removed — was hardcoded
// fake reviews used in the social-proof section. Replaced with an honest
// "WHY STEHLEN" trust grid that points to verifiable facts. Re-add real
// testimonials when verified review data (Okendo / Junip) is wired.

export default async function HomePage() {
  const categories = getCategories();
  const popularVehicles = getPopularVehicles();
  // Cycle 14AA (Mike-O14AA F-7 MAJOR): if the visitor already has a
  // saved vehicle, flip the YMM band to a "shop your truck" CTA pointing
  // to the vehicle hub instead of asking them to re-pick year/make/model.
  const savedVehicle = await getCurrentVehicle().catch(() => null);
  const vehicleSlug = savedVehicle
    ? `${savedVehicle.make.toLowerCase()}-${savedVehicle.model
        .toLowerCase()
        .replace(/\s+/g, "-")}`
    : null;

  // Cycle 14BE-fix7 (Mike Mission 2 + Jordan F-6 + Marcus #6): returning-
  // customer personalization band. When a vehicle is saved, pull a handful
  // of in-stock products that fit their vehicle from the most-shopped
  // categories so the homepage stops treating returning visitors as
  // anonymous. Champions reactivated by email land here — they need a
  // "we remember you" moment, not the same anonymous grid.
  const subModelAnswers = savedVehicle
    ? await getSubModelAnswers(savedVehicle.id ?? "").catch(() => [])
    : [];
  const personalizationPicks = savedVehicle
    ? await (async () => {
        // Most-shopped categories per Marcus's order-volume reference.
        const POPULAR = [
          "tonneau-covers",
          "bull-guards-grille-guards",
          "trailer-hitches",
          "truck-bed-mats",
        ];
        const results = await Promise.all(
          POPULAR.map((slug) =>
            getCollection(slug, 8, {
              vehicle: savedVehicle,
              subModelAnswers,
              hideMismatches: true,
            }).catch(() => null),
          ),
        );
        const seen = new Set<string>();
        const picks: CatalogProduct[] = [];
        for (const c of results) {
          if (!c) continue;
          const pick = c.products.find(
            (p) => p.inventory > 0 && !seen.has(p.handle),
          );
          if (pick) {
            seen.add(pick.handle);
            picks.push(pick);
          }
          if (picks.length >= 4) break;
        }
        return withFitment(picks, savedVehicle, subModelAnswers);
      })()
    : [];

  return (
    <main>
      {/* HERO — Cycle 10 (owner): mobile was breaking every word onto its
          own line because the inner column was width:40% (= ~160px on a
          400px viewport). Using a className-based container so we can switch
          column width responsively without inline-style media query hacks. */}
      <section
        className="hero-section"
        style={{
          position: "relative",
          background: "var(--color-background)",
          borderBottom: "1px solid var(--color-border)",
          overflow: "hidden",
        }}
      >
        {/* Cycle 13 (owner brand-mark): objectPosition moved to .hero-bg-img
            in globals.css so it can be responsive — desktop shifts right to
            expose the embossed "STEHLEN" panel into the negative space beside
            the content column; mobile shifts right so the mark remains visible
            even at portrait crop. */}
        <Image
          src="/images/hero-stehlen.jpg"
          alt=""
          aria-hidden="true"
          fill
          priority
          // Cycle 14AM (Diana): sizes="100vw" was over-serving the 3840-bucket
          // and then upscaling a small cached thumbnail. Tuned ladder caps the
          // request at the actual rendered width per breakpoint. quality=88
          // delivers ~200KB on the restored 1920×839 source. fetchPriority
          // hints the browser to prioritize the byte stream over below-fold
          // assets. objectFit moved to .hero-bg-img CSS where objectPosition
          // already lives.
          sizes="(min-width: 1920px) 1920px, (min-width: 1440px) 1440px, (min-width: 1280px) 1280px, 100vw"
          quality={88}
          fetchPriority="high"
          className="hero-bg-img"
        />
        <div
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            /* Cycle 13 (owner brand-mark): pull the transparent stop in from 55%
             to 48% so the embossed STEHLEN panel gets clean light once the
             image is shifted right via .hero-bg-img objectPosition. */
          background:
              "linear-gradient(90deg, rgba(10,10,10,0.88) 0%, rgba(10,10,10,0.72) 18%, rgba(10,10,10,0.25) 36%, rgba(10,10,10,0) 48%)",
          }}
        />
        {/* Mobile-only full-width darken so headline stays legible when the
            text column spans the entire viewport. Hidden on md+. */}
        <div
          aria-hidden="true"
          className="hero-mobile-darken"
          style={{
            position: "absolute",
            inset: 0,
            /* Cycle 13 (owner brand-mark): angled gradient stays dark top-left
             (headline legibility) but opens up bottom-right so the embossed
             brand mark is partially visible on mobile after objectPosition
             shifts to 68% right. */
          background:
              "linear-gradient(160deg, rgba(10,10,10,0.82) 0%, rgba(10,10,10,0.72) 45%, rgba(10,10,10,0.38) 100%)",
          }}
        />
        <div
          aria-hidden="true"
          style={{
            position: "absolute",
            inset: 0,
            backgroundImage:
              "linear-gradient(rgba(245,168,35,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(245,168,35,0.04) 1px, transparent 1px)",
            backgroundSize: "64px 64px",
            mixBlendMode: "screen",
          }}
        />

        <div
          className="container-x"
          style={{
            position: "relative",
            zIndex: 2,
            // Cycle 14AM (Diana hero pass): padding tightened from 72/80 to
            // 56/56; minHeight inline override removed so the .hero-section
            // CSS ladder is the single source of truth for height.
            paddingTop: 56,
            paddingBottom: 56,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "flex-start",
          }}
        >
          <div className="hero-col">
            <div
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 12,
                marginBottom: 20,
              }}
            >
              <span
                style={{
                  width: 32,
                  height: 2,
                  background: "var(--color-primary)",
                }}
              />
              <span
                className="mono"
                style={{
                  fontSize: 11,
                  letterSpacing: "0.18em",
                  color: "rgba(255,255,255,0.85)",
                  fontWeight: 500,
                }}
              >
                STEHLEN AUTO · SINCE 2015
              </span>
            </div>
            <h1
              className="text-5xl md:text-7xl"
              style={{
                fontFamily: "var(--font-display)",
                lineHeight: 0.92,
                letterSpacing: "-0.025em",
                textTransform: "uppercase",
                fontWeight: 800,
                textShadow: "0 4px 32px rgba(0,0,0,0.6)",
              }}
            >
              BUILT TOUGH.
              <br />
              <span style={{ color: "var(--color-primary)" }}>BOLT ON.</span>
              <br />
              DRIVE OFF.
            </h1>
            <p
              style={{
                color: "rgba(255,255,255,0.85)",
                fontSize: 16,
                maxWidth: 520,
                marginTop: 18,
                lineHeight: 1.55,
                textShadow: "0 2px 8px rgba(0,0,0,0.6)",
              }}
            >
              Heavy-duty vehicle accessories engineered from cold-rolled
              steel. No drilling required. Fitment guaranteed for your
              vehicle.
            </p>

            {/* Cycle 14X+ (partner feedback): the inline YMM card inside
                the hero was redundant with the yellow "FIND PARTS FOR
                YOUR RIDE" YMM band immediately below the hero, and the
                YEAR / MAKE / MODEL chips looked like text inputs but
                were modal-trigger buttons — partners reported it as
                "the search box is not working." Removed entirely; the
                yellow band on the next section is the single source of
                truth for inline YMM on the home page. */}

            {/* Cycle 14AM (Diana + owner): retired the trust micro-row
                and the dual ghost-button CTA pair from the hero. The
                trust pills duplicate the full <TrustRow /> mounted below
                the categories section; carrying them here was visual
                noise. The two ghost CTAs were splitting attention and
                violating the one-yellow-accent-per-viewport rule. Now:
                ONE primary yellow CTA, focused on the slogan above. */}
            {/* Cycle 14BB-fix1 (Jordan F-003): when a vehicle is saved,
                the YMM band below renders the yellow "SHOP PARTS THAT FIT"
                CTA. Keeping the hero CTA primary-yellow puts two yellow
                CTAs in the same viewport, splitting attention and
                violating the one-yellow-per-viewport rule. Demote the
                hero CTA to outlined when the higher-intent "shop your
                vehicle" path is already surfaced below.
                Cycle 14BB-fix5 (Jordan F-NNN-3): plain outlined `btn` on
                the dark hero gradient at mobile dropped contrast below
                WCAG floor in outdoor light. Layer a translucent white
                fill + stronger border so the demoted CTA stays legible
                without competing with the yellow band below. */}
            <Link
              href="/collections"
              className={savedVehicle ? "btn btn-lg" : "btn btn-primary btn-lg"}
              style={
                savedVehicle
                  ? {
                      marginTop: 28,
                      background: "rgba(255,255,255,0.10)",
                      borderColor: "rgba(255,255,255,0.55)",
                      color: "#fff",
                    }
                  : { marginTop: 28 }
              }
            >
              SHOP ALL PARTS <Icons.arrowR size={14} />
            </Link>
          </div>
        </div>
      </section>

      {/* High-contrast YMM band — Cycle 11 (owner mobile QA): redundant with
          the hero YMM card on mobile (two pickers within 700px scroll). Hidden
          below md+; on desktop it serves a different purpose as a wide
          full-width CTA strip. */}
      <section
        className="hidden md:block"
        style={{
          background: "var(--color-primary)",
          color: "#0a0a0a",
          borderBottom: "1px solid var(--color-border)",
        }}
      >
        <div
          className="container-x"
          style={{
            display: "flex",
            alignItems: "center",
            gap: 24,
            paddingTop: 24,
            paddingBottom: 24,
            flexWrap: "wrap",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 14, flex: "0 0 auto" }}>
            <Icons.shield size={22} />
            <div>
              <div
                className="mono"
                style={{
                  fontSize: 11,
                  letterSpacing: "0.16em",
                  fontWeight: 700,
                  opacity: 0.7,
                }}
              >
                {savedVehicle ? "SHOP YOUR VEHICLE" : "FITMENT GUARANTEED"}
              </div>
              <div
                style={{
                  fontFamily: "var(--font-display)",
                  fontSize: 22,
                  fontWeight: 800,
                  textTransform: "uppercase",
                  letterSpacing: "-0.01em",
                  lineHeight: 1.1,
                }}
              >
                {savedVehicle
                  ? `${savedVehicle.year} ${savedVehicle.make} ${savedVehicle.model}`
                  : "Find parts for your ride"}
              </div>
            </div>
          </div>
          {savedVehicle && vehicleSlug ? (
            <div
              style={{
                display: "flex",
                gap: 8,
                flex: 1,
                minWidth: 0,
                flexWrap: "wrap",
                justifyContent: "flex-end",
              }}
            >
              <Link
                href={`/vehicle/${vehicleSlug}`}
                className="btn btn-lg"
                style={{
                  background: "#0a0a0a",
                  color: "var(--color-primary)",
                  fontFamily: "var(--font-display)",
                  fontSize: 13,
                  fontWeight: 800,
                  letterSpacing: "0.04em",
                  padding: "0 22px",
                  height: 44,
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 8,
                  border: 0,
                }}
              >
                SHOP PARTS THAT FIT <Icons.arrowR size={14} />
              </Link>
              <YmmButton
                ariaLabel="Change vehicle"
                style={{
                  height: 44,
                  background: "transparent",
                  color: "#0a0a0a",
                  border: "1px solid rgba(0,0,0,0.3)",
                  borderRadius: "var(--radius-sm)",
                  fontFamily: "var(--font-display)",
                  fontSize: 12,
                  letterSpacing: "0.1em",
                  padding: "0 18px",
                  display: "flex",
                  alignItems: "center",
                  cursor: "pointer",
                }}
              >
                CHANGE VEHICLE
              </YmmButton>
            </div>
          ) : (
          <div
            className="grid grid-cols-2 md:grid-cols-[1fr_1fr_1fr_auto]"
            style={{ gap: 8, flex: 1, minWidth: 0 }}
          >
            {(["YEAR ▾", "MAKE ▾"] as const).map((label) => (
              <YmmButton
                key={label}
                ariaLabel={`Pick ${label.replace(" ▾", "")}`}
                style={{
                  height: 44,
                  background: "#0a0a0a",
                  color: "#fff",
                  borderRadius: "var(--radius-sm)",
                  fontFamily: "var(--font-display)",
                  fontSize: 12,
                  letterSpacing: "0.1em",
                  padding: "0 14px",
                  textTransform: "uppercase",
                  display: "flex",
                  alignItems: "center",
                  cursor: "pointer",
                  border: 0,
                }}
              >
                {label}
              </YmmButton>
            ))}
            <YmmButton
              className="col-span-2 md:col-span-1"
              ariaLabel="Pick model"
              style={{
                height: 44,
                background: "#0a0a0a",
                color: "#fff",
                borderRadius: "var(--radius-sm)",
                fontFamily: "var(--font-display)",
                fontSize: 12,
                letterSpacing: "0.1em",
                padding: "0 14px",
                textTransform: "uppercase",
                display: "flex",
                alignItems: "center",
                cursor: "pointer",
                border: 0,
              }}
            >
              MODEL ▾
            </YmmButton>
            <YmmButton
              className="col-span-2 md:col-span-1"
              ariaLabel="Open vehicle picker"
              style={{
                height: 44,
                background: "#0a0a0a",
                color: "var(--color-primary)",
                borderRadius: "var(--radius-sm)",
                fontFamily: "var(--font-display)",
                fontSize: 13,
                fontWeight: 800,
                letterSpacing: "0.04em",
                padding: "0 22px",
                display: "inline-flex",
                alignItems: "center",
                justifyContent: "center",
                gap: 8,
                cursor: "pointer",
                border: 0,
              }}
            >
              SEARCH <Icons.arrowR size={14} />
            </YmmButton>
          </div>
          )}
        </div>
      </section>

      {/* Cycle 14X+ (partner feedback): the BEST SELLERS THIS MONTH grid
          used to live here as the 01 section. Partners want the lead
          slot to be SHOP BY CATEGORY (browse-first), with a feature-
          items video clip eventually replacing this. Removed for now;
          add back as a video block when the warehouse delivers footage. */}

      {/* Cycle 14BE-fix7 (Mike Mission 2 + Jordan F-6 + Marcus #6):
          returning-customer personalization band. Surfaces 3-4 in-stock
          fitment-verified products for the customer's saved vehicle so
          repeat visitors don't see the same anonymous grid as cold
          traffic. Marcus: this is the mechanism reactivation email spend
          converts on. Hidden when no garage vehicle is set OR no
          fitment-verified picks were returned (e.g., exotic vehicle with
          no catalog coverage). */}
      {savedVehicle && personalizationPicks.length > 0 && (
        <section
          style={{
            background: "var(--color-surface)",
            borderTop: "1px solid var(--color-border)",
            borderBottom: "1px solid var(--color-border)",
          }}
        >
          <div
            className="container-x"
            style={{ paddingTop: 48, paddingBottom: 48 }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "baseline",
                justifyContent: "space-between",
                flexWrap: "wrap",
                gap: 8,
                marginBottom: 20,
              }}
            >
              <div>
                <div
                  className="eyebrow"
                  style={{ marginBottom: 8, color: "var(--color-primary)" }}
                >
                  WELCOME BACK
                </div>
                <h2
                  style={{
                    fontFamily: "var(--font-display)",
                    fontSize: "clamp(24px, 4vw, 36px)",
                    textTransform: "uppercase",
                    letterSpacing: "-0.02em",
                    margin: 0,
                  }}
                >
                  Continue your build for the {savedVehicle.year}{" "}
                  {savedVehicle.make} {savedVehicle.model}
                </h2>
              </div>
              <Link
                href={vehicleSlug ? `/vehicle/${vehicleSlug}` : "/collections"}
                className="mono"
                style={{
                  fontSize: 12,
                  letterSpacing: "0.08em",
                  textTransform: "uppercase",
                  color: "var(--color-primary)",
                  textDecoration: "none",
                  fontWeight: 700,
                }}
              >
                See all {savedVehicle.model} parts →
              </Link>
            </div>
            <div
              className="grid grid-cols-2 md:grid-cols-4"
              style={{ gap: 16 }}
            >
              {personalizationPicks.slice(0, 4).map((p) => (
                <ProductCard key={p.sku} product={p} vehicle={savedVehicle} />
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Reactivation banner — Cycle 14AN (Diana): warm-shift from cool
          --color-surface-2 (#1a1a1a, indistinguishable from body) to
          --color-surface-warm (#16140f, slight warm undertone). At the
          same lightness tier it now registers as a distinct stripe
          instead of disappearing into the body, AND sets up the
          dark→light tone break against the upcoming light category
          section below — the RoughCountry warm-off-black principle.
          Cycle 14AU F-8 (Jordan): hide for visitors with a saved garage
          vehicle. The "Bought from us on eBay or Amazon?" pitch targets
          marketplace cross-shoppers — once a customer has saved a
          vehicle they're already engaged on stehlenauto.com and the
          band becomes noise above the categories grid. */}
      {!savedVehicle && (
      <section
        style={{
          background: "var(--color-surface-warm)",
          borderTop: "1px solid var(--color-border)",
          borderBottom: "1px solid var(--color-border)",
        }}
      >
        <div
          className="container-x"
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            paddingTop: 20,
            paddingBottom: 20,
            flexWrap: "wrap",
            gap: 16,
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
            <div
              style={{ width: 4, height: 36, background: "var(--color-primary)" }}
            />
            <div>
              <div
                className="mono"
                style={{
                  fontSize: 11,
                  color: "var(--color-primary)",
                  letterSpacing: "0.14em",
                }}
              >
                WELCOME BACK
              </div>
              <div style={{ fontSize: 14, fontWeight: 500 }}>
                Bought from us on eBay or Amazon? You&apos;ll find the same parts
                here — at lower prices.
              </div>
            </div>
          </div>
          <Link href="/welcome-back" className="btn btn-sm">
            CLAIM 10% RETURNING-CUSTOMER OFFER →
          </Link>
        </div>
      </section>
      )}

      {/* Categories grid — Cycle 14AN (Diana section-tone audit): this is
          THE light-section break in the home page. Six consecutive flat-
          black sections were reading as one undifferentiated dark wall;
          flipping this single section to warm off-white gives the eye a
          place to rest and announces "this is a real catalog, not a
          billboard." Wrapper carries the bg + border so it reads as one
          visually distinct stripe; container-x stays inside for layout. */}
      <section
        style={{
          background: "var(--color-section-light)",
          color: "var(--color-section-light-fg)",
          borderTop: "1px solid var(--color-border)",
          borderBottom: "1px solid var(--color-border)",
        }}
      >
        <div
          className="container-x"
          style={{ paddingTop: 64, paddingBottom: 72 }}
        >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "baseline",
            marginBottom: 24,
          }}
        >
          <div>
            <div
              className="eyebrow"
              style={{
                marginBottom: 8,
                color: "var(--color-section-light-muted)",
              }}
            >
              BROWSE
            </div>
            <h2
              style={{
                fontFamily: "var(--font-display)",
                fontSize: 32,
                textTransform: "uppercase",
                letterSpacing: "-0.01em",
              }}
            >
              SHOP BY CATEGORY
            </h2>
          </div>
          <Link
            href="/collections"
            className="mono"
            style={{
              fontSize: 12,
              color: "var(--color-section-light-muted)",
              letterSpacing: "0.08em",
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              whiteSpace: "nowrap", // Cycle 11 — owner mobile QA: was wrapping to "VIEW / ALL"
              flexShrink: 0,
              minHeight: 44,
              paddingBlock: 12,
            }}
          >
            VIEW ALL <Icons.arrowR size={12} />
          </Link>
        </div>
        <div
          className="grid grid-cols-2 md:grid-cols-4"
          style={{
            // Cycle 14AN-fix2 (Diana round 3): killed the cluster border
            // and the painted dark gap entirely. With the section now at
            // a true warm cream (#e6e0d6) and the tile bg matching it,
            // tile separation comes from a per-tile box-shadow lift, not
            // a containing rectangle. 12px gap lets the section bg
            // breathe between tiles instead of a 1px dark seam — closer
            // to RoughCountry's open-grid pattern, no cage.
            gap: 12,
          }}
        >
          {categories.map((cat) => (
            <Link
              key={cat.slug}
              href={`/collections/${cat.slug}`}
              style={{
                // Cycle 14AN-fix2 (Diana round 3): tile bg still matches
                // section so the tile and section share one warm-cream
                // plane. Replaced the dark cluster border with a
                // per-tile shadow lift — 1px hairline at 6% black plus a
                // 3px ambient drop. On the new #e6e0d6 cream, this casts
                // visibly (the prior near-white bg ate the same shadow);
                // hover bumps it for tap affordance.
                background: "var(--color-section-light)",
                color: "var(--color-section-light-fg)",
                padding: 0,
                display: "flex",
                flexDirection: "column",
                position: "relative",
                overflow: "hidden",
                aspectRatio: "1.05",
                boxShadow:
                  "0 1px 3px rgba(0, 0, 0, 0.10), 0 0 0 1px rgba(0, 0, 0, 0.06)",
              }}
            >
              <div
                // Cycle 14AN (Diana): category tiles now use the
                // category-img-bg class (warm light-grey #e8e6e3) instead
                // of product-img-bg (#f4f4f4 cool with grid). On the new
                // light section background, the warm grey reads as a
                // subtly recessed image area — no false white-frame
                // around each product photo. Collection product cards
                // keep product-img-bg unchanged.
                className="category-img-bg"
                style={{
                  flex: 1,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  minHeight: 100,
                  position: "relative",
                  overflow: "hidden",
                }}
              >
                {cat.image ? (
                  <Image
                    src={cat.image}
                    alt={cat.name}
                    fill
                    sizes="(min-width: 768px) 25vw, 50vw"
                    style={{ objectFit: "contain", padding: "4%" }}
                  />
                ) : (
                  <span
                    className="mono"
                    style={{
                      color: "#999",
                      fontSize: 11,
                      letterSpacing: "0.12em",
                    }}
                  >
                    {cat.name.toUpperCase()}
                  </span>
                )}
              </div>
              {/* Cycle 11 (owner mobile QA): row used to put title + arrow
                  in a flex space-between, which made long names wrap mid-word
                  and pushed the arrow onto its own line. Now title clamps to
                  exactly 2 lines (consistent tile heights), arrow lives in
                  bottom-right via absolute positioning. */}
              {/* Cycle 14X+ (Mike-O11 F-1 NIT): wrapper padding moved from
                  the outer Link onto this title strip so the image fills
                  edge-to-edge. */}
              <div
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  justifyContent: "space-between",
                  gap: 8,
                  // Cycle 14AN (Diana): label strip padding 12/14 → 14/16,
                  // type 13→15, weight 600→700. At 25vw tile width on
                  // mobile a 13px mono cap was reading as supporting
                  // detail. 15/700 reads as a real navigation choice.
                  padding: "14px 16px",
                  // Cycle 14AN-fix (Diana recovery): explicit bg + color
                  // on the strip — was transparent + inheriting the
                  // section's dark fg color, rendering "TONNEAU COVERS"
                  // dark-on-dark inside a then-still-dark tile strip.
                  // Now bg matches the light section and text is anchored
                  // directly to the dark fg token, no inheritance race.
                  background: "var(--color-section-light)",
                  color: "var(--color-section-light-fg)",
                }}
              >
                <div
                  className="mono"
                  style={{
                    fontSize: 15,
                    fontWeight: 700,
                    letterSpacing: "0.04em",
                    textTransform: "uppercase",
                    lineHeight: 1.3,
                    minHeight: "2.6em",
                    display: "-webkit-box",
                    WebkitLineClamp: 2,
                    WebkitBoxOrient: "vertical",
                    overflow: "hidden",
                    flex: 1,
                  }}
                >
                  {cat.name}
                </div>
                <Icons.arrowR size={14} />
              </div>
            </Link>
          ))}
        </div>
        </div>
      </section>

      {/* Trust row */}
      <TrustRow />

      {/* Popular vehicles */}
      <section className="container-x" style={{ paddingTop: 64, paddingBottom: 64 }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "baseline",
            marginBottom: 24,
          }}
        >
          <div>
            <div className="eyebrow" style={{ marginBottom: 8 }}>
              BROWSE
            </div>
            <h2
              style={{
                fontFamily: "var(--font-display)",
                fontSize: 32,
                textTransform: "uppercase",
                letterSpacing: "-0.01em",
              }}
            >
              SHOP BY POPULAR VEHICLE
            </h2>
          </div>
          <Link
            href="/collections"
            className="mono"
            style={{
              fontSize: 12,
              color: "var(--color-muted)",
              letterSpacing: "0.08em",
              whiteSpace: "nowrap",
              flexShrink: 0,
              display: "inline-flex",
              alignItems: "center",
              minHeight: 44,
              paddingBlock: 12,
            }}
          >
            ALL MAKES →
          </Link>
        </div>
        <div
          className="grid grid-cols-2 md:grid-cols-4"
          style={{ gap: 8 }}
        >
          {popularVehicles.map((v) => {
            // Cycle 14X+ (partner feedback): popular-vehicle cards used to
            // be text-only. Map make+model → latest-gen photo from
            // /public/images/vehicle-gens (the same shots the /vehicle/[slug]
            // hub uses) so customers visually pick their truck. When a make
            // doesn't yet have a gen photo (Tundra/Sierra/Frontier today),
            // fall back to the truck silhouette icon.
            const slug = `${v.make.toLowerCase()}-${v.model.toLowerCase().replace(/\s+/g, "-")}`;
            const photo = POPULAR_VEHICLE_PHOTOS[slug] ?? null;
            return (
            <Link
              key={`${v.make}-${v.model}`}
              href={`/vehicle/${slug}`}
              style={{
                display: "flex",
                flexDirection: "column",
                background: "var(--color-surface)",
                border: "1px solid var(--color-border)",
                borderRadius: "var(--radius-md)",
                overflow: "hidden",
              }}
            >
              <div
                className="product-img-bg"
                style={{
                  position: "relative",
                  aspectRatio: "1.6",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  overflow: "hidden",
                }}
              >
                {photo ? (
                  <Image
                    src={photo}
                    alt={`${v.make} ${v.model}`}
                    fill
                    sizes="(min-width: 768px) 25vw, 50vw"
                    style={{ objectFit: "cover" }}
                  />
                ) : (
                  <div style={{ color: "var(--color-muted)" }}>
                    <Icons.truck size={36} sw={1.5} />
                  </div>
                )}
              </div>
              <div
                style={{
                  display: "flex",
                  flexDirection: "column",
                  gap: 4,
                  padding: 14,
                }}
              >
                <div
                  className="mono"
                  style={{
                    fontSize: 10,
                    color: "var(--color-muted)",
                    letterSpacing: "0.1em",
                  }}
                >
                  {v.make.toUpperCase()}
                </div>
                <div style={{ fontSize: 18, fontWeight: 600 }}>{v.model}</div>
                {/* Cycle 14AL (owner): year range removed from this card.
                    The customer doesn't browse by year here — they pick a
                    model, then the vehicle hub asks them for year. Keeping
                    the year row added visual noise without helping the
                    decision. */}
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    marginTop: 4,
                  }}
                >
                  <span
                    className="mono"
                    style={{
                      fontSize: 10,
                      color: "var(--color-primary)",
                      letterSpacing: "0.08em",
                    }}
                  >
                    SHOP &rarr;
                  </span>
                  <Icons.arrowR size={12} />
                </div>
              </div>
            </Link>
          );
          })}
        </div>
      </section>

      {/* Cycle 14X+ (partner feedback): removed the "BUILT BY DRIVERS,
          FOR DRIVERS" trust grid AND the "JUST RESTOCKED" product rail.
          The trust messages those cards carried (fitment guarantee,
          drilling-free install, ships from CA/NV/TX) are already covered
          by the TrustRow above and the footer. The JUST RESTOCKED rail
          duplicated catalog discovery from the SHOP BY CATEGORY grid
          higher on the page. */}
    </main>
  );
}
